pipeline{
 agent any

    stages{
        stage('hello'){
            steps{
                sh'''
                    echo "hellow guys good morning"
                '''
            }

        }
    }
}